### ISSUE TITLE
在Android7.0以上的版本 不能正常运行

### ISSUE THREAD

**Issue by CoderBCat** [Alex-Cin/RippleWaveView#1]
如题

**Comment by Alex-Cin** [comment]
我在简书上写了 这个 回复。 7.0 关于 无线循环的写法，更严格了。 怪我学艺不精。。
.setRepeatMode(ValueAnimator.REVERSE);
.setRepeatCount(Integer.MAX_VALUE);

改成
.setRepeatCount(ValueAnimator.INFINITE);//无限循环
.setRepeatMode(ValueAnimator.INFINITE);//

**Comment by Alex-Cin** [comment]
我在简书上写了 这个 回复。 7.0 关于 无线循环的写法，更严格了。 怪我学艺不精。。
.setRepeatMode(ValueAnimator.REVERSE);
.setRepeatCount(Integer.MAX_VALUE);

改成
.setRepeatCount(ValueAnimator.INFINITE);//无限循环
.setRepeatMode(ValueAnimator.INFINITE);//
